### ISSUE TITLE
nil in field is not allowed.

### ISSUE THREAD

**Issue by davidkhala** [davidkhala/fabric-common-chaincode-golang#7]
```
GatewayError: 2 UNKNOWN: evaluate call to endorser returned error: chaincode response 500, Error handling success response. Value did not match schema:
1. return.Attrs.attrs: Invalid type. Expected: object, given: null
    at newGatewayError (common/nodejs/fabric-gateway/node_modules/@hyperledger/fabric-gateway/dist/gatewayerror.js:53:12)
    at Object.callback (common/nodejs/fabric-gateway/node_modules/@hyperledger/fabric-gateway/dist/client.js:93:67)
    at Object.onReceiveStatus (common/nodejs/fabric-gateway/node_modules/@grpc/grpc-js/build/src/client.js:192:36)
    at Object.onReceiveStatus (common/nodejs/fabric-gateway/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (common/nodejs/fabric-gateway/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /home/david/delphi-fabric/common/nodejs/fabric-gateway/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

nil as response is allowed. But nil as field in struct is not allowed

**Comment by davidkhala** [comment]
nil as response is allowed. But nil as field in struct is not allowed

**Comment by davidkhala** [comment]
Alternative give empty value(s) to indicate unassigned fields.
